### ISSUE TITLE
TestBridge.pm wrong precedence

### ISSUE THREAD

**Issue by iabyn** [Perl-Toolchain-Gang/CPAN-Meta-YAML#6]
CPAN::Meta::YAML 0.019 has just been merged into bleadperl, and it's emitting several warnings from two lines:

```
Useless use of string eq in void context at t/lib/TestBridge.pm line 351.
Useless use of string eq in void context at t/lib/TestBridge.pm line 356.
```

This is because both those lines have code along the lines of:

`ok(cond1 or cond2, "description")`

which, due to the low precedence of 'or', is being parsed as:

`ok(cond1 or (cond2, "description"))`

The immediate fix is trivial (replace 'or' with '||'), but I have no opinions on the deeper issue of the second condition not being checked and whether it requires further work on the code or test.

**Comment by karenetheridge** [comment]
I've just released a new version of YAML-Tiny; when this hits the index I can roll a new CPAN-Meta-YAML as well and then merge it into blead.
